
<header>
	<h2>Dude's Tasks Application</h2>
	<div class="addTaskDiv" >
		<button id="addTaskButton" onclick="addTaskFunction()">
		<a href="javascript:;"><i class="iconMod" style="<?php echo "background-image: url('" . get_png("addTaskPlus.png") ."')" ?>"></i></a>
		</button>
	</div>	
</header>

<main>
	<table id="tasksList">
		<thead id="headerTasksList">
			<tr>
			<th class="taskId">
				Task Number
			</th>
			<th class="taskCreator">
				Task Creator
			</th>
			<th class="taskType">
				Task Type
			</th>
			<th class="taskDescription">
				Task Description
			</th>
			<th class="taskCreationDate">
				Task Creation Date
			</th>
			<th class="taskFinalizationDate">
				Task Finalization Date
			</th>
			<th class="divMod">
				Modify 
			</th>
			<th class="divDel">
				Delete
			</th>
			</tr>			
		</thead>
		<!-- Starting List of Tasks Elements -->
		<tbody>
			
		<!-- STARTING ROW 1 -->
		<tr class="rowTasksList">
			<td class="taskId">
				1
			</td>
			<td class="taskCreator">
				TheDude
			</td>
			<td class="taskType">
				Ongoing
			</td>
			<td class="taskDescription">
				Finish the sprint 3 with JSON persistency
			</td>
			<td class="taskCreationDate">
				2023-12-31 19:14
			</td>
			<td class="taskFinalizationDate">
				2023-12-31 22:14
			</td>
			<td class="divMod">
				<button class="buttonMod" onclick="modPopUpFunction()">
				<a href="javascript:;"><i class="iconMod" style="<?php echo "background-image: url('" . get_png("modify-i.png") ."')" ?>"></i></a>
				</button>
			</td>
			<td class="divDel" >
				<button class="buttonDel" onclick="delTaskFunction()">
				<a href=""><i class="iconMod" style="<?php echo "background-image: url('" . get_png("delete-i.png") ."')" ?>"></i></a>
				</button>
			</td>				
		</tr>
		<!-- FINISHIN ROW 1 -->
		
		
		
		<!-- STARTING ROW 2 -->
		<tr class="rowTasksList">
			<td class="taskId">
				2
			</td>
			<td class="taskCreator">
				TheDude
			</td>
			<td class="taskType">
				Pending
			</td>
			<td class="taskDescription">
				Finish the sprint 3 with  MySQL persistency
			</td>
			<td class="taskCreationDate">
				2024-01-02 19:14
			</td>
			<td class="taskFinalizationDate">
				2024-01-03 19:14
			</td>
			<td class="divMod">
				<button class="buttonMod" onclick="modPopUpFunction()">
				<a href="javascript:;"><i class="iconMod" style="<?php echo "background-image: url('" . get_png("modify-i.png") ."')" ?>"></i></a>
				</button>
			</td>
			<td class="divDel" >
				<button class="buttonDel" onclick="delTaskFunction()">
				<a href=""><i class="iconMod" style="<?php echo "background-image: url('" . get_png("delete-i.png") ."')" ?>"></i></a>
				</button>
			</td>				
		</tr>
		<!-- FINISHIN ROW 2 -->
		
		
		
		</tbody>
	</table>
	
	
	<!-- Formular in order to be able to modify the tasks -->
	<div id="modFormDiv">
	<div id="innerModFormDiv">
	<div id="contentModFormDiv">
	<form action="#" method="post">
		<div class="groupForm">
			<div class="inputGroup">
				<label for="modTaskId">Task ID:</label><br>
				<input type="text" id="modTaskId" name="modTaskId" value="1" readonly>
			</div>
			
			<div class="inputGroup">
					<label for="modTaskCreator">Task Creator:</label><br>
					<input type="text" id="modTaskCreator" name="modTaskCreator" value="Dude">
			</div>
			
			<div class="inputGroup">
					<label for="modTaskType">Task Type:</label><br>
					<select id="modTaskType" name="modTaskType">
						<option value="Pending">Pending</option>
						<option value="Ongoing">Ongoing</option>
						<option value="Finished">Finished</option>
					</select>
			</div>
		
		</div>
		
		<div class="groupForm">
			<div class="inputGroup">
				<label for="modTaskDescription">Task Description:</label><br>
				<textarea rows="5" id="modTaskDescription" name="modTaskDescription" value="Finish the sprint 3 with JSON Persistency">
				</textarea><br>
			</div>
		</div>
		
		<div class="groupForm">
			<div class="inputGroup">
				<label for="modCreationDate">Creation Date of the task:</label><br>
				<input
					type="datetime-local"
					id="modCreationDate"
					name="modCreationDate"
					/>
			</div>
			<div class="inputGroup">
				<label for="modFinalizationDate">Finalization Date of the task:</label><br>
				<input
					type="datetime-local"
					id="modFinalizationDate"
					name="modFinalizationDate"
					/>
				</div>
			</div>
			
		<div class="groupForm">
			<div class="inputGroup">
				<button id="submitModForm" type="submit" name="submit"  value="modTask">Modify Task</button>
			</div>
		</div>
		
		
		<div class="groupForm">
			<div class="inputGroup">
				<button id="modFormCloseButton" onclick="closeFormPopUpFunction()">
				Cancel
				</button>
			</div>
		</div>
		
	</form>
		
	</div>
	</div>
	</div>
	
	<!-- Formular in order to be able to modify the tasks  END-->
	
	
	
	<!-- Formular in order to be able to add a task -->
	<div id="addFormDiv">
	<div id="innerAddFormDiv">
	<div id="contentAddFormDiv">
	<form action="#" method="post">
		<div class="groupForm">
			<div class="inputGroup">
				<label for="addTaskId">Task ID:</label><br>
				<input type="text" id="addTaskId" name="addTaskId" value="1" readonly>
			</div>
			
			<div class="inputGroup">
					<label for="addTaskCreator">Task Creator:</label><br>
					<input type="text" id="addTaskCreator" name="addTaskCreator" value="Dude">
			</div>
			
			<div class="inputGroup">
					<label for="addTaskType">Task Type:</label><br>
					<select id="addTaskType" name="addTaskType">
						<option value="Pending">Pending</option>
						<option value="Ongoing">Ongoing</option>
						<option value="Finished">Finished</option>
					</select>
			</div>
		
		</div>
		
		<div class="groupForm">
			<div class="inputGroup">
				<label for="addTaskDescription">Task Description:</label><br>
				<textarea rows="5" id="addTaskDescription" name="addTaskDescription" value="Finish the sprint 3 with JSON Persistency">
				</textarea><br>
			</div>
		</div>
		
		<div class="groupForm">
			<div class="inputGroup">
				<label for="addCreationDate">Creation Date of the task:</label><br>
				<input
					type="datetime-local"
					id="addCreationDate"
					name="addCreationDate"
					/>
			</div>
			<div class="inputGroup">
				<label for="addFinalizationDate">Finalization Date of the task:</label><br>
				<input
					type="datetime-local"
					id="addFinalizationDate"
					name="addFinalizationDate"
					/>
				</div>
			</div>
			
		<div class="groupForm">
			<div class="inputGroup">
				<button id="submitAddForm" type="submit" name="submit" value="addTask">Add Task</button>
			</div>
		</div>
		
		
		<div class="groupForm">
			<div class="inputGroup">
				<button id="addFormCloseButton" onclick="closeAddFormPopUpFunction()">
				Cancel
				</button>
			</div>
		</div>
		
	</form>
		
	</div>
	</div>
	</div>
	
	<!-- Formular in order to be able to add a tasks  END-->
	
	
</main>

<footer>
</footer>

