
<header>
	Dude's Tasks Application Header
</header>

<main>
	<table id="tasksList">
		<thead id="headerTasksList">
			<tr>
			<th class="taskNumber">
				Task Number
			</th>
			<th class="taskCreator">
				Task Creator
			</th>
			<th class="taskType">
				Task Type
			</th>
			<th class="taskDescription">
				Task Description
			</th>
			<th class="taskCreationDate">
				Task Creation Date
			</th>
			<th class="taskFinalizationDate">
				Task Finalization Date
			</th>
			<th class="divMod">
				Modify 
			</th>
			<th class="divDel">
				Delete
			</th>
			</tr>			
		</thead>
		<!-- Starting List of Tasks Elements -->
		<tbody>
		<tr class="rowTasksList">
			<td class="taskNumber">
				1
			</td>
			<td class="taskCreator">
				TheDude
			</td>
			<td class="taskType">
				Active
			</td>
			<td class="taskDescription">
				Finish the sprint 3 with JSON persistency
			</td>
			<td class="taskCreationDate">
				2023-12-31 19:14
			</td>
			<td class="taskFinalizationDate">
				2023-12-31 22:14
			</td>
			<td class="divMod">
				<a href=""><i class="iconMod" style="<?php echo "background-image: url('" . get_png("modify-i.png") ."')" ?>"></i></a>
			</td>
			<td class="divDel" >
				<a href=""><i class="iconMod" style="<?php echo "background-image: url('" . get_png("delete-i.png") ."')" ?>"></i></a>
			</td>				
		</tr>
		</tbody>
		
		
	</table>
</main>

<footer>
</footer>

